# PLot QC improvement with added FC

In [4]:
library(tidyverse)
library(ggplot2)

In [5]:
qc_asm_unphased <- read_tsv("../../assembly/qc/qc_flowcells.tsv")
head(qc_asm_unphased)

Rows: 17064 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (6): chromosome, metric, haplotype, asm_method, asm_name, source
dbl (1): value

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  chromosome metric                   value  haplotype asm_method
1 chr1       variants                 375069 both      phased_verkko
2 chr1       phased                   250097 both      phased_verkko
3 chr1       unphased                   9780 both      phased_verkko
4 chr1       singletons                    0 both      phased_verkko
5 chr1       blocks                        1 both      phased_verkko
6 chr1       variant_per_block_median 250097 both      phased_verkko
  asm_name    source
1 TUE_02_01UL whatshap_stats
2 TUE_02_01UL whatshap_stats
3 TUE_02_01UL whatshap_stats
4 TUE_02_01UL whatshap_stats
5 TUE_02_01UL whatshap_stats
6 TUE_02_01UL whatshap_stats

In [6]:
qc_asm <- read_tsv("../../assembly/qc/qc_flowcells.tsv")
head(qc_asm)

Rows: 17064 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (6): chromosome, metric, haplotype, asm_method, asm_name, source
dbl (1): value

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  chromosome metric                   value  haplotype asm_method
1 chr1       variants                 375069 both      phased_verkko
2 chr1       phased                   250097 both      phased_verkko
3 chr1       unphased                   9780 both      phased_verkko
4 chr1       singletons                    0 both      phased_verkko
5 chr1       blocks                        1 both      phased_verkko
6 chr1       variant_per_block_median 250097 both      phased_verkko
  asm_name    source
1 TUE_02_01UL whatshap_stats
2 TUE_02_01UL whatshap_stats
3 TUE_02_01UL whatshap_stats
4 TUE_02_01UL whatshap_stats
5 TUE_02_01UL whatshap_stats
6 TUE_02_01UL whatshap_stats

In [10]:
source("../scripts/03_plot_mapping_stats.R")

Warning message in file(filename, "r", encoding = encoding):
“cannot open file '../scripts/03_plot_mapping_stats.R': No such file or directory”

ERROR: Error in file(filename, "r", encoding = encoding): cannot open the connection